service: edinet-test

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1

package:
  exclude:
    - package.json
    - package-lock.json
    - serverless.yml
    - .vscode/**
    - node_modules/**

functions:
  test:
    handler: handler.index

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-python-requirements
